---
# tasks file for cisco_user_compliance
- name: Ensure admin users exist
  cisco.ios.ios_user:
    name: "{{ local_user }}"
    hashed_password:
      type: 5
      value: "{{ local_pass }}"
    update_password: on_create
    privilege: 15
    state: present
    purge: "{{ purge_users }}"
  register: add_user_result

- name: Save IOS
  cisco.ios.ios_command:
    commands: write memory
  when: add_user_result is changed
